spring:
  application:
    name: schedule-api
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8081

custom:
  file-path: src/main/resources/files/schedule.csv